// <auto-generated />
using System;
using API_Formulary.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Formulary.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20240102024018_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("API_Formulary.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CantidadEgresados")
                        .HasColumnType("int");

                    b.Property<string>("ColegioCurso")
                        .HasColumnType("longtext");

                    b.Property<string>("ColegioLocalidad")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ColegioNivel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ColegioNombre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Comision")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime");

                    b.Property<string>("MedioEntrega")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("Vendedor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("API_Formulary.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ItemId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("API_Formulary.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContractId" }, "ContractId");

                    b.HasIndex(new[] { "ItemId" }, "ItemId");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("API_Formulary.Models.Item", b =>
                {
                    b.HasOne("API_Formulary.Models.Contract", null)
                        .WithMany("Items")
                        .HasForeignKey("ContractId");

                    b.HasOne("API_Formulary.Models.Item", null)
                        .WithMany("Items")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("API_Formulary.Models.Order", b =>
                {
                    b.HasOne("API_Formulary.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("API_Formulary.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Contract");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("API_Formulary.Models.Contract", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("API_Formulary.Models.Item", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
